#!/bin/sh
p=( $@ )
len=${#p[@]}
cmd=${p[@]:0:$len}
$cmd
result=$?
if [ $result == 0 ]; then
	notify-send "Monitor results" "Command \"$1\" executed successfully."
else
	notify-send "Monitor results" "Command \"$1\" failed."
fi
