FROM node:8-alpine as basis
RUN apk update && apk add gcc g++ musl-dev make python 
USER node
RUN mkdir ~/.npm-global
RUN npm config set prefix '~/.npm-global'
RUN npm install -g aglio

FROM node:8-alpine
USER node
COPY --from=basis /home/node/.npm-global /home/node/.npm-global
ENTRYPOINT ["/home/node/.npm-global/bin/aglio"]
