/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.giovannicuriel.tinytools.kotlin

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.get(), "app should have a greeting")
    }
}
